id = "selene"
name = "Selene"
description = "The open source coding agent."
version = "1.2.18"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/selene"

[agent_servers.selene]
name = "Selene"
icon = "./icons/selene.svg"

[agent_servers.selene.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/selene/releases/download/v1.2.18/selene-darwin-arm64.zip"
cmd = "./selene"
args = ["acp"]

[agent_servers.selene.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/selene/releases/download/v1.2.18/selene-darwin-x64.zip"
cmd = "./selene"
args = ["acp"]

[agent_servers.selene.targets.linux-aarch64]
archive = "https://github.com/anomalyco/selene/releases/download/v1.2.18/selene-linux-arm64.tar.gz"
cmd = "./selene"
args = ["acp"]

[agent_servers.selene.targets.linux-x86_64]
archive = "https://github.com/anomalyco/selene/releases/download/v1.2.18/selene-linux-x64.tar.gz"
cmd = "./selene"
args = ["acp"]

[agent_servers.selene.targets.windows-x86_64]
archive = "https://github.com/anomalyco/selene/releases/download/v1.2.18/selene-windows-x64.zip"
cmd = "./selene.exe"
args = ["acp"]
