name: selene

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  selene:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /selene') ||
      startsWith(github.event.comment.body, '/selene')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run selene
        uses: anomalyco/selene/github@latest
        env:
          SELENE_API_KEY: ${{ secrets.SELENE_API_KEY }}
          SELENE_PERMISSION: '{"bash": "deny"}'
        with:
          model: selene/claude-opus-4-5
